### ISSUE TITLE
Issue with installation in ubuntu

### ISSUE THREAD

**Issue by maederayati2** [noirello/pyorc#23]
The package will not build on ubuntu 18.04. The error seems to be related to missing files in _pyorc directory. The error message is this:

`In file included from src/_pyorc/_pyorc.cpp:1:
    src/_pyorc/Reader.h:7:10: fatal error: 'orc/OrcFile.hh' file not found
    #include "orc/OrcFile.hh"`

I could install the library on Mac (which I guess it was using wheel) but my docker container with ubuntu 18.04 keeps failing.

**Comment by noirello** [comment]
You should either upgrade pip to 19.0 or newer, which can handle `manylinux2010` wheels or build the package from source. That will require a C++ complier, cmake and some extra steps that are described in the [docs](https://pyorc.readthedocs.io/en/latest/install.html#install-from-source).

Also, you might need to install tzdata and set the localtime in the container. (See Issue #13)

**Comment by maederayati2** [comment]
Yep, that fixed the issue, thank you very much!!
